version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./backend:/var/www
#    depends_on:
#      - mysql
#      - redis
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx_server
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    depends_on:
      - backend
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: vue_app
    restart: unless-stopped
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev -- --host
    networks:
      - app-network

#  mysql:
#    image: mysql:8.0
#    container_name: mysql_db
#    restart: unless-stopped
#    environment:
#      MYSQL_DATABASE: laravel
#      MYSQL_ROOT_PASSWORD: root
#      MYSQL_PASSWORD: secret
#      MYSQL_USER: laravel
#    ports:
#      - "3306:3306"
#    volumes:
#      - dbdata:/var/lib/mysql
#    networks:
#      - app-network

#  redis:
#    image: redis:alpine
#    container_name: redis_cache
#    restart: unless-stopped
#    ports:
#      - "6379:6379"
#    networks:
#      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata: